### ISSUE TITLE
Front-end route planning

### ISSUE THREAD

**Issue by stevenpetryk** [partygoer/partygoer-web#3]
@andrewhamon, I'd like some help planning the routes for the front-end:

Currently, the routes are as such:

```
/               # => nothing
/:partySlug     # => voting page
/:partySlug/tv  # => TV page
/:partySlug/new # => track page
```

Overall, we need an app state for each of the following:

* Home page (which will have a form for quick party creation)
* Parties list (with geolocation)
* Party details page (after a party is created, to show instructions on how to connect to the player and to optionally add location information)
* Voting screen
* TV screen
* New track screen

I propose this:

```
/                   # => home/party creation page
/parties            # => local/public parties
/:partySlug/details # => party setup information
/:partySlug         # => voting page
/:partySlug/tv      # => TV page
/:partySlug/new     # => track page
```

It's a little bit annoying that /:partySlug is a specific state (voting), but I think that's best for mobile users, since they won't have to type very much.

Am I missing anything?

**Comment by andrewhamon** [comment]
:+1:

**Comment by stevenpetryk** [comment]
Good talk.
