### ISSUE TITLE
Create party details page

### ISSUE THREAD

**Issue by stevenpetryk** [partygoer/partygoer-web#6]
This is the page that will exist at /:partySlug/details. Its purposes include:

* Indicate how to display the queue on your TV
* Indicate where guests need to go to vote
* Show how to start the partygoer player
* Optionally allow users to make the party public and enter location data

Here's the initial mockup (without location options):

![partygoer home page](https://cloud.githubusercontent.com/assets/1724000/7897870/93245fe0-06bb-11e5-916c-e455fdfaebbc.png)

@andrewhamon check it out, yo

**Comment by stevenpetryk** [comment]
**With party details**

![party details page](https://cloud.githubusercontent.com/assets/1724000/7898076/8982abde-06c2-11e5-9f14-c5b65d935a35.png)

**Comment by andrewhamon** [comment]
I think you are misunderstanding what the public setting does. All parties can be accessed by anyone if they know the URL. Being public simply allows a party to be shown in the index, which only works when a user provides their location. Maybe we should eliminate the option (in the UI) and assume that if the user provides their location, they want to be public, and then on settings page let them turn it off only after they have provided a location.
